### ISSUE TITLE
The handlerRoot option has been added to prevent building.

### ISSUE THREAD

**Issue by chimame** [theapexlab/ra-data-blitz#8]
## Overview
Build was possible in 0.0.9, but not in 0.0.10(Sorry, it seems that [my fix](https://github.com/theapexlab/ra-data-blitz/pull/4) was incorrect.)

## Problem
The handlerRoot option has been changed to expand the scope of dynamic import to include node_modules. As a result, this library and others are built again, and the following error occurs.
https://github.com/theapexlab/ra-data-blitz/blob/9b92507d6459c04b83d6e7490d854cdea7ccb872/src/utils/getHandler.ts#L9

```
error - ./node_modules/@theapexlab/ra-data-blitz/lib/utils/getEntityNameFromResource.d.ts.map
Module parse failed: Unexpected token (1:10)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> {"version":3,"file":"getEntityNameFromResource.d.ts","sourceRoot":"","sources":["../../src/utils/getEntityNameFromResource.ts"],"names":[],"mappings":"AAGA,eAAO,MAAM,yBAAyB,aAAc,MAAM,WAEzD,CAAC"}
Could not find files for / in .next/build-manifest.json
Could not find files for / in .next/build-manifest.json
```

## Countermeasure
I think it is better to limit the places to load. For example, limit it to `app/react-admin`.
It would be nice if we could use webpack's [webpackInclude](https://webpack.js.org/api/module-methods/#dynamic-expressions-in-import) or something similar, but since we are building with TypeScript, we think that would be difficult.

**Comment by m4tty-d** [comment]
I didn't have the time to test your PR thoroughly, so thanks for reporting!

I pushed a hotfix regarding the issue, it's available in v0.0.11. 🎉

The functionality stayed but changed a little bit. The import has to start with `app/`, but after that, you can still specify a handlerRoot.

Can you confirm that it's working for you, too? @chimame

**Comment by chimame** [comment]
@m4tty-d Thank you for your support.

I have confirmed that it works fine using v0.0.11 :tada: 
I will report back if there is anything I can do to help.

**Comment by chimame** [comment]
@m4tty-d My way of checking was not good.
The latest v0.0.11 had the problem.

It is not possible to load the handler regardless of the use of the `handlerRoot` option. The reason is that it is `app` instead of `app/`, so it is not subject to dynamic import (or more precisely, require) of webpack.

**Comment by m4tty-d** [comment]
@chimame
Well, that's frustrating. I did test v0.0.11 locally with npm link, so I don't know how I missed this.
I pushed another fix (v0.0.12), hopefully, it will finally be good. 🤞

**Comment by chimame** [comment]
@m4tty-d Thank you for helping to support this.

We have confirmed the changes and behavior in v0.0.12.
There was no problem with the behavior without adding the API route that caused the problem. However, when the API route was added, the [issue](https://github.com/theapexlab/ra-data-blitz/issues/3) was still not resolved.

The cause of this issue is a bit difficult to find, because it is not the TypeScript code, but the compiled code that webpack loads.

```js
// lib/utils/getHandler.js
return [2 /*return*/, Promise.resolve().then(function () { return __importStar(require("app/".concat(handlerRoot.length ? "".concat(handlerRoot, "/") : '').concat(resource, "/").concat(folder, "/").concat(method).concat(plural ? (0, getPluralEntityName_1.getPluralEntityName)(entityName) : entityName))); })];
```
